// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Brute() {
  return window['go']['main']['App']['Brute']();
}

export function Fuzz(arg1, arg2, arg3) {
  return window['go']['main']['App']['Fuzz'](arg1, arg2, arg3);
}

export function FuzzStop() {
  return window['go']['main']['App']['FuzzStop']();
}

export function GetHistoryDump(arg1) {
  return window['go']['main']['App']['GetHistoryDump'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Parser(arg1) {
  return window['go']['main']['App']['Parser'](arg1);
}

export function Proxy(arg1) {
  return window['go']['main']['App']['Proxy'](arg1);
}

export function Raw(arg1, arg2, arg3) {
  return window['go']['main']['App']['Raw'](arg1, arg2, arg3);
}

export function SendToRepeater(arg1) {
  return window['go']['main']['App']['SendToRepeater'](arg1);
}

export function Swagger(arg1) {
  return window['go']['main']['App']['Swagger'](arg1);
}

export function Verify(arg1, arg2) {
  return window['go']['main']['App']['Verify'](arg1, arg2);
}
