// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Brute() {
  return window['go']['main']['App']['Brute']();
}

export function Decoder(arg1, arg2) {
  return window['go']['main']['App']['Decoder'](arg1, arg2);
}

export function Fuzz(arg1, arg2, arg3) {
  return window['go']['main']['App']['Fuzz'](arg1, arg2, arg3);
}

export function FuzzStop() {
  return window['go']['main']['App']['FuzzStop']();
}

export function GetAttackDump(arg1, arg2) {
  return window['go']['main']['App']['GetAttackDump'](arg1, arg2);
}

export function GetHistoryDump(arg1) {
  return window['go']['main']['App']['GetHistoryDump'](arg1);
}

export function GetProxyPort() {
  return window['go']['main']['App']['GetProxyPort']();
}

export function Intruder(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Intruder'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Parser(arg1) {
  return window['go']['main']['App']['Parser'](arg1);
}

export function Proxy(arg1) {
  return window['go']['main']['App']['Proxy'](arg1);
}

export function Raw(arg1, arg2, arg3) {
  return window['go']['main']['App']['Raw'](arg1, arg2, arg3);
}

export function SendToIntruder(arg1) {
  return window['go']['main']['App']['SendToIntruder'](arg1);
}

export function SendToRepeater(arg1) {
  return window['go']['main']['App']['SendToRepeater'](arg1);
}

export function Settings(arg1) {
  return window['go']['main']['App']['Settings'](arg1);
}

export function Swagger(arg1) {
  return window['go']['main']['App']['Swagger'](arg1);
}

export function TaskList(arg1) {
  return window['go']['main']['App']['TaskList'](arg1);
}

export function Verify(arg1, arg2) {
  return window['go']['main']['App']['Verify'](arg1, arg2);
}
